services:
  - type: web
    name: uploader  # Your service name
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port=$PORT file_loader.wsgi:application
